name: Code Quality Check

on:
    pull_request:
        branches:
            - dev

jobs:
    lint:
        name: Run TypeScript and Lint Checks
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci

            - name: Install types
              run: npm -i --save-dev @types/node

            - name: Run TypeScript type check
              run: npm run verify

            - name: Run Linter
              run: npm run lint

            - name: Check code formatting (optional)
              run: npm run format -- --check
